### ISSUE TITLE
https://go.dev/s/using-guru

### ISSUE THREAD

**Issue by nikolaydubina** [nikolaydubina/go-recipes#139]

**Comment by alexandear** [comment]
I think, this issue is not relevant any more.

From the https://go.dev/s/using-guru document:
> cmd/guru was [deleted](https://github.com/golang/go/issues/65880) in March 2024. It has long been superseded by [gopls](https://github.com/golang/tools/tree/master/gopls), a language (LSP) server for Go that works with a wide range of editors.

**Comment by nikolaydubina** [comment]
good point. closing this
