### ISSUE TITLE
Add links to the project

### ISSUE THREAD

**Issue by nikandfor** [nikolaydubina/go-recipes#96]
Hi Nikolay

Thanks for adding my project to the list.

A little remark about your list: you are adding a link to the author in a project description, which is pleasant for the author but could be more beneficial for your user. As a user navigating through the list, he will want to open some of the projects and check them out (read the readme, check the code, read issues, etc.), and there is no link for that now.

Cheers!

**Comment by nikolaydubina** [comment]
Hi,

Yes, absolutely. Adding links to all projects soon.

-- Nikolay
